version: '2'

services:
  identity.service:
    image: eshop/identity
    environment:
      - SpaClient=http://localhost:5104
      - ConnectionStrings__DefaultConnection=Server=identity.data;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word
      #- MvcClient=http://104.40.62.65:5100             #Remote: VM Needs to have public access at 5105. 
      - MvcClient=http://localhost:5100                 #Local: You need a entry in windows host file to run identity in local docker. 
    ports:
      - "5105:5105"
    depends_on:
      - identity.data

  sql.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
