version: '2'

services:
  ordering.api:
    image: eshop/ordering.api
    environment:
      - ConnectionString=Server=ordering.data;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
    ports:
      - "5102:80"
    depends_on:
      - ordering.data

  ordering.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5432:1433"

  identity.service:
    image: eshop/identity
    environment:
      - SpaClient=http://localhost:5104
      - ConnectionString=Server=identity.data;Database=aspnet-Microsoft.eShopOnContainers;User Id=sa;Password=Pass@word
      #- MvcClient=http://104.40.62.65:5100             #Remote: VM Needs to have public access at 5105. 
      - MvcClient=http://localhost:5100                 #Local: You need a entry in windows host file to run identity in local docker. 
    ports:
      - "5105:5105"
    depends_on:
      - identity.data

  identity.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"